### ISSUE TITLE
Browsers support

### ISSUE THREAD

**Issue by wan54** [ForgeRock/appAuthHelper#13]
Please add in the README list of the browsers supported since ServiceWorker and IDB are used.

**Comment by jakefeasel** [comment]
Thanks for your suggestion, sorry I didn't reply earlier. There are actually two ways to build the library - one for modern browsers (e.g. those with Service Worker support) and a "compat" build for older browsers (mainly, IE 11). You can see these build options as scripts within package.json. The modern build is considerably smaller than the compat version, as you would expect.

The build files I have checked into the source are using the "compat" build.

**Comment by cameron-martin** [comment]
`appauthhelper/appAuthHelperCompat` doesn't work in  IE11 because it depends on `appauthhelper/IdentityProxyCore` which uses arrow functions. Shall I send a PR to fix this?

**Comment by jakefeasel** [comment]
Really? That's surprising... I thought that's what babel was supposed to be fixing for me.... I would really appreciate it if you could take a look at why babel isn't solving this problem. If, for some reason, we can't make babel do it for us then I would be happy for a PR. Thanks!

**Comment by cameron-martin** [comment]
From looking at the scripts in the package.json, only the bundled versions are run through babel. The docs [seem to suggest](https://github.com/ForgeRock/appAuthHelper#supporting-legacy-browsers) that importing the non-bundled version, `appauthhelper/appAuthHelperCompat`, should work in IE11.

**Comment by jakefeasel** [comment]
Commit fda9b42 fixes the babel config and includes new versions of the bundle files based on the compat build.

**Comment by cameron-martin** [comment]
Thanks a lot for this.

**Comment by jakefeasel** [comment]
I think there is a misunderstanding about the expectations here. The pre-built "bundles" shipped here and produced by running `npm run build-compat` are IE 11-compatible. There are no arrow functions in them:

```
grep "=>" *Bundle.js
// returns nothing
```

That being said, I realize that you aren't using these pre-built bundles, but are instead using webpack / browserify to load it with require. In that case, I believe it is up to your build config to specify how you want to handle the ES6->ES5 transformation. See this highly-related SO post for more details:

https://stackoverflow.com/a/60395448/808921

**Comment by cameron-martin** [comment]
Sure, that's what I ended up doing. It's a shame, at least as far as I know, that we don't have a solid way of dealing with publishing ES2015+ packages yet.

The last that I heard around it was the following two articles:

* https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages
* https://2ality.com/2017/06/pkg-esnext.html

However, the first option is not a full solution and a TC39 member doesn't seem to think the second is viable: https://2ality.com/2017/06/pkg-esnext.html#comment-3341521675

**Comment by jakefeasel** [comment]
Those are good links, and provide helpful background info. Thanks for that. I just assumed that it was a normal part of the build process. Having to target ES5 for all projects that expected to be consumed as a node_module dependency is pretty terrible for everyone. That being said, if that is how things work these days, I would be open to converting my current ES6 usages down to ES5.

**Comment by cameron-martin** [comment]
It is pretty terrible for everyone, but I'm not aware of a better way at the moment. Would be good to get other people's opinions on this, however. cc @adam-cyclones @cerebrl @chuckmasucci, @jaredjensen as a selection, idk who's most knowledgeable on this.

**Comment by cerebrl** [comment]
Hey @cameron-martin, I'm definitely not an expert on this subject, but I'm familiar with the pain :)

The projects with which I've been involved, have always published transpiled code with the modularity preserved along with a bundled file for convenience. I can't remember a project were we published the actual raw source code, which, admittedly, is unfortunate but necessary.

Some projects I work on, though, do ship an ES Module version and a CommonJS version. Both versions are fully transpiled, but the former has the ES import-export syntax preserved.

Again, just my personal experience. Cheers!

**Comment by sam2k2002** [comment]
Hi Folks - Very interesting insights here. Was it intended that the fix for OPENIDM-15150 apply to the Platform UIs as well? I ask as it seems none of the Platform UIs work in IE11. This includes standalone build and PaaS. Known issue? @jakefeasel @cameron-martin
