### ISSUE TITLE
Usage without iFrame?

### ISSUE THREAD

**Issue by LUS1N** [ForgeRock/appAuthHelper#2]
Hi,

is it possible to use this library without rendering an iframe?

Our authentication endpoint (ADFS server) doesn't allow to be rendered in one by returning X-Frame-Options: Deny, so an option for redirecting or a pop up would be nice.

**Comment by jakefeasel** [comment]
This library passes prompt=none into the url provided to the iframe. This should cause the AS to always respond with a 302 redirect back to your redirect_uri. X-Frame-Options won't apply in that case.

This is similar to the process described here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-silent-aad and here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-spa

I don't have any first-hand experience with ADFS but I would assume it works similar to how Microsoft describes the process there.
