### ISSUE TITLE
appAuthHelper loses reference to `reg.active`

### ISSUE THREAD

**Issue by fetimo** [ForgeRock/appAuthHelper#26]
```
setInterval(function () {
  // prevents the service worker thread from becoming idle and losing
  // the references we just passed into it.
  reg.active.postMessage({"message": "keepAlive"});
}, 1000);
```

Sporadically this seems to error every second saying that `reg.active` is undefined. Initially I thought it was down to my development environment occasionally getting confused with hot reloading but I've now witnessed it in a deployed environment too. 

I guess the quick fix would be to check that `postMessage` exists on `reg.active` but I'm not sure what is leading `reg.active` to sometimes be undefined in the first place. Any ideas?

**Comment by jakefeasel** [comment]
Can you share more details about the browser environment? Vendor + version? Also, any conditions you have observed that lead to this? I think I can formulate a fix that will handle this case, but I would be more confident in the approach if I could reproduce it.

**Comment by jakefeasel** [comment]
@fetimo I haven't been able to reproduce the error myself, but I have a PR which I think will account for the possibility. Could you try this out and see if it solves it for you? Thanks
