### ISSUE TITLE
Option to use idToken for resourceServer instead of accessToken

### ISSUE THREAD

**Issue by akuma12** [ForgeRock/appAuthHelper#4]
First, I want to say thank you for a truly awesome library. You've made my life a million times easier since we've made the decision to migrate to the PKCE auth flow in our SPAs.

The issue that I'm running into is that with our IdP, PingFederate, when using OIDC, it wants to authenticate using the idToken rather than the accessToken. The access_token is really only used to hit the `userinfo` endpoint to get more information than JWT provides. In `appAuthHelperFetchTokens.js`, if you have a resourceServer configured in the appAuthHelper settings, it sets the resourceServer token to the access_token in the IndexedDB. Would it be possible to add an optional config setting to override that to use idToken instead?

I'd propose to add a new config item called "resourceServerAuthToken", with possible values of "accessToken" and "idToken" (to match the keys in the token_endpoint_response object), defaulting to "accessToken", as well as validating the value. I'll create a PR with these changes for your review.

Thanks!

**Comment by ve7jtb** [comment]
The ID token should not be used as a access token.  Most AS can emit JWT as access tokens.  They need to be audianced to RS and not the client. 

Conflating the two tokens can introduce possible security issues.

**Comment by akuma12** [comment]
> The ID token should not be used as a access token. Most AS can emit JWT as access tokens. They need to be audianced to RS and not the client.
> 
> Conflating the two tokens can introduce possible security issues.

I discovered that we had a misconfiguration on our IdP that was causing it to only publish the id_token's signing certificate rather than the access_token's. This led us to believe that we needed to use the id_token for authn.

Thanks!
